# Generated by Django 5.2.8 on 2025-11-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(blank=True, max_length=25, null=True)),
                ('paterno', models.CharField(blank=True, max_length=15, null=True)),
                ('materno', models.CharField(blank=True, max_length=15, null=True)),
                ('estatus', models.IntegerField(choices=[(1, 'Activo'), (2, 'Inactivo'), (3, 'Cancelado')], default=1)),
            ],
            options={
                'db_table': 'contratos',
            },
        ),
    ]
